# Import

In [12]:
import numpy, scipy
import pandas as pd
numpy.set_printoptions(precision=3) 

# Data Preparation

In [2]:
real_df = pd.read_csv('aps_failure_training_set.csv')

In [ ]:
real_df

In [ ]:
real_df.describe()

In [3]:
df_na_rem = pd.read_csv('aps_failure_training_set.csv', na_values = ["na"])

In [ ]:
df_na_rem

In [4]:
df_na_rem.describe()

aa_000        ab_000        ac_000        ad_000        ae_000  \
count  6.000000e+04  13671.000000  5.666500e+04  4.513900e+04  57500.000000   
mean   5.933650e+04      0.713189  3.560143e+08  1.906206e+05      6.819130   
std    1.454301e+05      3.478962  7.948749e+08  4.040441e+07    161.543373   
min    0.000000e+00      0.000000  0.000000e+00  0.000000e+00      0.000000   
25%    8.340000e+02      0.000000  1.600000e+01  2.400000e+01      0.000000   
50%    3.077600e+04      0.000000  1.520000e+02  1.260000e+02      0.000000   
75%    4.866800e+04      0.000000  9.640000e+02  4.300000e+02      0.000000   
max    2.746564e+06    204.000000  2.130707e+09  8.584298e+09  21050.000000   

             af_000        ag_000        ag_001        ag_002        ag_003  \
count  57500.000000  5.932900e+04  5.932900e+04  5.932900e+04  5.932900e+04   
mean      11.006817  2.216364e+02  9.757223e+02  8.606015e+03  8.859128e+04   
std      209.792592  2.047846e+04  3.420053e+04  1.503220e+05  7.617312e+05   
min        0.000000  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%        0.000000  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%        0.000000  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%        0.000000  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
max    20070.000000  3.376892e+06  4.109372e+06  1.055286e+07  6.340207e+07   

           ...             ee_002        ee_003        ee_004        ee_005  \
count      ...       5.932900e+04  5.932900e+04  5.932900e+04  5.932900e+04   
mean       ...       4.454897e+05  2.111264e+05  4.457343e+05  3.939462e+05   
std        ...       1.155540e+06  5.433188e+05  1.168314e+06  1.121044e+06   
min        ...       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%        ...       2.936000e+03  1.166000e+03  2.700000e+03  3.584000e+03   
50%        ...       2.337960e+05  1.120860e+05  2.215180e+05  1.899880e+05   
75%        ...       4.383960e+05  2.182320e+05  4.666140e+05  4.032220e+05   
max        ...       7.793393e+07  3.775839e+07  9.715238e+07  5.743524e+07   

             ee_006        ee_007        ee_008        ee_009        ef_000  \
count  5.932900e+04  5.932900e+04  5.932900e+04  5.932900e+04  57276.000000   
mean   3.330582e+05  3.462714e+05  1.387300e+05  8.388915e+03      0.090579   
std    1.069160e+06  1.728056e+06  4.495100e+05  4.747043e+04      4.368855   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
25%    5.120000e+02  1.100000e+02  0.000000e+00  0.000000e+00      0.000000   
50%    9.243200e+04  4.109800e+04  3.812000e+03  0.000000e+00      0.000000   
75%    2.750940e+05  1.678140e+05  1.397240e+05  2.028000e+03      0.000000   
max    3.160781e+07  1.195801e+08  1.926740e+07  3.810078e+06    482.000000   

             eg_000  
count  57277.000000  
mean       0.212756  
std        8.830641  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max     1146.000000  

[8 rows x 170 columns]

In [5]:
df_na_rem.isnull().sum()

class         0
aa_000        0
ab_000    46329
ac_000     3335
ad_000    14861
ae_000     2500
af_000     2500
ag_000      671
ag_001      671
ag_002      671
ag_003      671
ag_004      671
ag_005      671
ag_006      671
ag_007      671
ag_008      671
ag_009      671
ah_000      645
ai_000      629
aj_000      629
ak_000     4400
al_000      642
am_0        629
an_000      642
ao_000      589
ap_000      642
aq_000      589
ar_000     2723
as_000      629
at_000      629
          ...  
dl_000     4008
dm_000     4009
dn_000      691
do_000     2724
dp_000     2726
dq_000     2726
dr_000     2726
ds_000     2727
dt_000     2727
du_000     2726
dv_000     2726
dx_000     2723
dy_000     2724
dz_000     2723
ea_000     2723
eb_000     4007
ec_00     10239
ed_000     9553
ee_000      671
ee_001      671
ee_002      671
ee_003      671
ee_004      671
ee_005      671
ee_006      671
ee_007      671
ee_008      671
ee_009      671
ef_000     2724
eg_000     2723
Length: 171, dtype: int6

# Dividing data into X and Y

In [6]:
X = df_na_rem.iloc[:, 1:].values
X

array([[7.66980000e+04,            nan, 2.13070644e+09, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.30580000e+04,            nan, 0.00000000e+00, ...,
        1.50000000e+03, 0.00000000e+00, 0.00000000e+00],
       [4.10400000e+04,            nan, 2.28000000e+02, ...,
        5.14000000e+02, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.12000000e+02, 0.00000000e+00, 2.13070643e+09, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.02920000e+04,            nan, 2.13070643e+09, ...,
        3.88422000e+05, 0.00000000e+00, 0.00000000e+00],
       [4.02220000e+04,            nan, 6.98000000e+02, ...,
        1.58000000e+02, 0.00000000e+00, 0.00000000e+00]])

In [7]:
Y = df_na_rem.iloc[:, 0].values
Y

array(['neg', 'neg', 'neg', ..., 'neg', 'neg', 'neg'], dtype=object)

# Handling Missing Data

In [9]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values=np.NaN, strategy='mean', axis=0)

In [10]:
X = imputer.fit_transform(X)

In [13]:
X

array([[7.670e+04, 7.132e-01, 2.131e+09, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [3.306e+04, 7.132e-01, 0.000e+00, ..., 1.500e+03, 0.000e+00,
        0.000e+00],
       [4.104e+04, 7.132e-01, 2.280e+02, ..., 5.140e+02, 0.000e+00,
        0.000e+00],
       ...,
       [1.120e+02, 0.000e+00, 2.131e+09, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [8.029e+04, 7.132e-01, 2.131e+09, ..., 3.884e+05, 0.000e+00,
        0.000e+00],
       [4.022e+04, 7.132e-01, 6.980e+02, ..., 1.580e+02, 0.000e+00,
        0.000e+00]])

# Applying Standardization

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()
scaled_X = scaler.fit_transform(X)

In [16]:
scaled_X

array([[ 1.194e-01, -6.686e-17,  2.297e+00, ..., -1.777e-01, -2.122e-02,
        -2.466e-02],
       [-1.807e-01, -6.686e-17, -4.609e-01, ..., -1.459e-01, -2.122e-02,
        -2.466e-02],
       [-1.258e-01, -6.686e-17, -4.609e-01, ..., -1.668e-01, -2.122e-02,
        -2.466e-02],
       ...,
       [-4.072e-01, -4.295e-01,  2.297e+00, ..., -1.777e-01, -2.122e-02,
        -2.466e-02],
       [ 1.441e-01, -6.686e-17,  2.297e+00, ...,  8.051e+00, -2.122e-02,
        -2.466e-02],
       [-1.314e-01, -6.686e-17, -4.609e-01, ..., -1.744e-01, -2.122e-02,
        -2.466e-02]])

# Doing Group By

In [ ]:
df_cat = df_na_rem.groupby('class')

In [ ]:
df_groups = {}
df_groups['pos'] = df_cat.get_group('pos')
df_groups['neg'] = df_cat.get_group('neg')

In [ ]:
df_groups['pos']

# Hot Encoding Y

In [18]:
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()

In [19]:
Y = labelEncoder.fit_transform(Y)

In [20]:
Y

array([0, 0, 0, ..., 0, 0, 0])

# Final

In [21]:
scaled_X

array([[ 1.194e-01, -6.686e-17,  2.297e+00, ..., -1.777e-01, -2.122e-02,
        -2.466e-02],
       [-1.807e-01, -6.686e-17, -4.609e-01, ..., -1.459e-01, -2.122e-02,
        -2.466e-02],
       [-1.258e-01, -6.686e-17, -4.609e-01, ..., -1.668e-01, -2.122e-02,
        -2.466e-02],
       ...,
       [-4.072e-01, -4.295e-01,  2.297e+00, ..., -1.777e-01, -2.122e-02,
        -2.466e-02],
       [ 1.441e-01, -6.686e-17,  2.297e+00, ...,  8.051e+00, -2.122e-02,
        -2.466e-02],
       [-1.314e-01, -6.686e-17, -4.609e-01, ..., -1.744e-01, -2.122e-02,
        -2.466e-02]])

In [22]:
Y

array([0, 0, 0, ..., 0, 0, 0])